[workspace]
members = [
    "src/zeus_common",
    "src/zeus_transport",
    "src/zeus_node",
    "src/zeus_client",
    "src/zeus_client_ffi",
    "examples/cosmic_drift",
    "examples/cosmic_drift_server",
]
resolver = "2"

